kind: Service
apiVersion: v1
metadata:
  name: python-app-loadbalancer
spec:
  type: LoadBalancer
  selector:
    name: python-app
  ports:
    - port: 8086
  externalTrafficPolicy: Cluster
  # loadBalancerSourceRanges:
  # - 145.58.210.14/32
  #clusterIP: 10.60.0.1 
  