kind: Service
apiVersion: v1
metadata:
  name: nodeport-python-app
  namespace: default
spec:
  type: NodePort
  selector:
    app: python-app
  ports:
    - port: 8086
      targetPort: 8086
      nodePort: 32000
  selector:
    name: python-app